### ISSUE TITLE
Github Campus

### ISSUE THREAD

**Issue by XomaDev** [himanshu007-creator/notify#3]
Hi, you are my Github Campus Expert, could we please have a talk?
Thanks

**Comment by himanshu007-creator** [comment]
Hey @XomaDev , kindly reach out on[ my Linkedin](https://www.linkedin.com/in/himanshu-here/), i dont feel this Github repo is the right place to talk, BTW Wish you a happy new year in advance 🥳 
I shall mark this closed.

incase above URL doesn;t work its
https://www.linkedin.com/in/himanshu-here/

**Comment by XomaDev** [comment]
Hi yes, I had actually messaged you, but you had not responded.
Thanks for the reply btw, are you on telegram?

Happy new year you too!

**Comment by himanshu007-creator** [comment]
Kindly share your linkedin profile, ill check the message @XomaDev
